apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atulbarge0708/helm-aws-chart.git
    targetRevision: main
    path: devops-chart-folder
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

